/* WARNING: This file is auto-generated by Kato compiler.
 * Do not modify this file manually.
 * Any changes will be overwritten on next compilation.
 */

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>


int main() {
    srand(time(NULL));
    int a;  // var int a = inpt("Enter a number 1 : ");
    printf("Enter a number 1 : ");
    scanf("%d", &a);
    int b;  // var int b = inpt("Enter a number 2 : ");
    printf("Enter a number 2 : ");
    scanf("%d", &b);
    char c;  // var char c = inpt("Enter a op : ");
    printf("Enter a op : ");
    scanf(" %c", &c);
    switch (c) {
        case '+':
            printf("%d", (a + b)); // print(*a* + *b*);
            break; // break;
        case '-':
            printf("%d", (a - b)); // print(*a* - *b*);
            break; // break;
        case '*':
            printf("%d", (a * b)); // print(*a* * *b*);
            break; // break;
        case '/':
            printf("%d", (a / b)); // print(*a* / *b*);
            break; // break;
    }
    return 0; // return 0;
}

