/* WARNING: This file is auto-generated by Kato compiler.
 * Do not modify this file manually.
 * Any changes will be overwritten on next compilation.
 */

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>


int main() {
    srand(time(NULL));
    int count = 0; // var int count = 0;
    while (1) {
        printf("Count: %d\n", count); // print("Count: *count*\n");
        count++; // count++;
        if ((count == 5)) {
            break; // stop;
        }
    }
    printf("Loop finished!\n"); // print("Loop finished!\n");
    return 0; // return 0;
}

