/* WARNING: This file is auto-generated by Kato compiler.
 * Do not modify this file manually.
 * Any changes will be overwritten on next compilation.
 */

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>


int main() {
    srand(time(NULL));
    int arr[3] = {10, 20, 30};
    int i = 0;
    while ((i < 3)) {
        printf("%d\n", arr[i]); // print(*arr[i]* "\n");
        i++;
    }
return 0;
}

