/* WARNING: This file is auto-generated by Kato compiler.
 * Do not modify this file manually.
 * Any changes will be overwritten on next compilation.
 */

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>

int kato_find(void* target, void* pattern);


int main() {
    srand(time(NULL));
    char* text = "Hello World"; // var string text = "Hello World";
    int pos = kato_find(text, "World"); // var int pos = find(text, "World");
    if ((pos != -1)) {
        printf("Found 'World' at position: %d\n", pos); // print("Found 'World' at position: *pos*\n");
    } else {
        printf("Not found\n"); // print("Not found\n");
    }
    char* data = "abcdefgh"; // var string data = "abcdefgh";
    int idx = kato_find(data, "cd"); // var int idx = find(data, "cd");
    printf("Found 'cd' at index: %d\n", idx); // print("Found 'cd' at index: *idx*\n");
    int notFound = kato_find(data, "xyz"); // var int notFound = find(data, "xyz");
    printf("Search for 'xyz': %d\n", notFound); // print("Search for 'xyz': *notFound*\n");
    char* sentence = "The quick brown fox"; // var string sentence = "The quick brown fox";
    int foxPos = kato_find(sentence, "fox"); // var int foxPos = find(sentence, "fox");
    printf("Found 'fox' at: %d\n", foxPos); // print("Found 'fox' at: *foxPos*\n");
    return 0; // return 0;
}

int kato_find(void* target, void* pattern) {
    char* t = (char*)target;
    char* p = (char*)pattern;
    if (!t || !p) return -1;
    int t_len = 0, p_len = 0;
    while (t[t_len]) t_len++;
    while (p[p_len]) p_len++;
    if (p_len == 0) return 0;
    for (int i = 0; i <= t_len - p_len; i++) {
        int match = 1;
        for (int j = 0; j < p_len; j++) {
            if (t[i + j] != p[j]) {
                match = 0;
                break;
            }
        }
        if (match) return i;
    }
    return -1;
}

