/* WARNING: This file is auto-generated by Kato compiler.
 * Do not modify this file manually.
 * Any changes will be overwritten on next compilation.
 */

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>


int main() {
    srand(time(NULL));
    int x = 10; // var int x = 10;
    int* px = &x; // var int* px = &x;
    printf("x = %d\n", x); // print("x = *x*\n");
    printf("Address of x: "); // print("Address of x: ");
    printf("%p", (void*)px); // print(px);
    printf("\n"); // print("\n");
    printf("Value via pointer = %d\n", (*px)); // print("Value via pointer = *px*\n");
    (*px) = 20;
    printf("x after change = %d\n", x); // print("x after change = *x*\n");
    int arr[3] = {1, 2, 3};
    int* pa = &arr[0]; // var int* pa = &arr[0];
    printf("Address of arr[0]: "); // print("Address of arr[0]: ");
    printf("%p", (void*)pa); // print(pa);
    printf("\n"); // print("\n");
    printf("arr[0] via pointer = %d\n", (*pa)); // print("arr[0] via pointer = *pa*\n");
    return 0; // return 0;
}

