from .codegen import ExpressionCodegen, StatementCodegen, FunctionCodegen


class CCompiler:
    def __init__(self, ast, stdlib_imports=None, c_imports=None):
        self.ast = ast
        self.indent_level = 0
        self.variables = {}
        self.stdlib_imports = stdlib_imports or set()
        self.c_imports = c_imports or set()
        self.uses_conversion = False
        self.function_return_types = {}
        
        self.expr_codegen = ExpressionCodegen(self)
        self.stmt_codegen = StatementCodegen(self, self.expr_codegen)
        self.func_codegen = FunctionCodegen(self, self.stmt_codegen)
    
    def indent(self):
        return "    " * self.indent_level
    
    def get_function_return_type(self, func_name):
        return self.function_return_types.get(func_name, "int")
    
    def compile(self):
        if hasattr(self.ast, 'c_imports'):
            for c_import in self.ast.c_imports:
                self.c_imports.add(c_import.header_name)
        
        for function in self.ast.functions:
            if function.params:
                function.param_types = self.func_codegen.infer_param_types(function, self.ast)
            function.return_type = self.func_codegen.infer_return_type(function)
            self.function_return_types[function.name] = function.return_type
        
        c_code = "/* WARNING: This file is auto-generated by Kato compiler.\n"
        c_code += " * Do not modify this file manually.\n"
        c_code += " * Any changes will be overwritten on next compilation.\n"
        c_code += " */\n\n"
        c_code += "#include <stdio.h>\n"
        c_code += "#include <string.h>\n"
        c_code += "#include <stdlib.h>\n"
        c_code += "#include <time.h>\n"
        
        for c_header in self.c_imports:
            c_code += f"#include <{c_header}>\n"
        
        c_code += "\n"
        
        if "filesystem" in self.stdlib_imports:
            from .std.filesystem import get_filesystem_functions
            c_code += get_filesystem_functions() + "\n"
        
        for function in self.ast.functions:
            if function.name != "main":
                c_code += self.func_codegen.get_function_signature(function) + ";\n"
        
        c_code += "\n"
        
        for function in self.ast.functions:
            c_code += self.func_codegen.compile_function(function)
            c_code += "\n"
        
        return c_code
