class tokens:
    tokens = {
        "func": "FUNCTION",
        "print": "PRINT",
        "return": "RETURN",
        "var": "VAR",
        "mass": "MASS",
        "int": "INT",
        "float": "FLOAT",
        "char": "CHAR",
        "string": "STRING_TYPE",
        "call": "CALL",
        "inpt": "INPT",
        "if": "IF",
        "elif": "ELIF",
        "else": "ELSE",
        "while": "WHILE",
        "import": "IMPORT",
        "switch": "SWITCH",
        "case": "CASE",
        "default": "DEFAULT",
    }